/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as MainSocialMediaRouteImport } from './routes/_main/social-media'
import { Route as MainSettingsRouteImport } from './routes/_main/settings'
import { Route as MainAnalyticsRouteImport } from './routes/_main/analytics'
import { Route as MainAboutRouteImport } from './routes/_main/about'
import { Route as MainTermsIndexRouteImport } from './routes/_main/terms/index'
import { Route as MainSubscriptionsIndexRouteImport } from './routes/_main/subscriptions/index'
import { Route as MainRolesIndexRouteImport } from './routes/_main/roles/index'
import { Route as MainQualificationsIndexRouteImport } from './routes/_main/qualifications/index'
import { Route as MainProvidersIndexRouteImport } from './routes/_main/providers/index'
import { Route as MainProfileIndexRouteImport } from './routes/_main/profile/index'
import { Route as MainPermissionsIndexRouteImport } from './routes/_main/permissions/index'
import { Route as MainPagesIndexRouteImport } from './routes/_main/pages/index'
import { Route as MainPackagesIndexRouteImport } from './routes/_main/packages/index'
import { Route as MainNotificationsIndexRouteImport } from './routes/_main/notifications/index'
import { Route as MainFaqsIndexRouteImport } from './routes/_main/faqs/index'
import { Route as MainDepartmentsIndexRouteImport } from './routes/_main/departments/index'
import { Route as MainCountriesIndexRouteImport } from './routes/_main/countries/index'
import { Route as MainContactsIndexRouteImport } from './routes/_main/contacts/index'
import { Route as MainClientsIndexRouteImport } from './routes/_main/clients/index'
import { Route as MainCitiesIndexRouteImport } from './routes/_main/cities/index'
import { Route as MainBannarsIndexRouteImport } from './routes/_main/bannars/index'
import { Route as MainAdminsIndexRouteImport } from './routes/_main/admins/index'
import { Route as MainPagesTypeRouteImport } from './routes/_main/pages/$type'
import { Route as MainPackagesIdRouteImport } from './routes/_main/packages/$id'
import { Route as MainCountriesIdRouteImport } from './routes/_main/countries/$id'
import { Route as MainCitiesIdRouteImport } from './routes/_main/cities/$id'
import { Route as MainPagesShowTypeRouteImport } from './routes/_main/pages/show/$type'
import { Route as MainPackagesShowIdRouteImport } from './routes/_main/packages/show/$id'
import { Route as MainClientsShowIdRouteImport } from './routes/_main/clients/show/$id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MainSocialMediaRoute = MainSocialMediaRouteImport.update({
  id: '/social-media',
  path: '/social-media',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAnalyticsRoute = MainAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTermsIndexRoute = MainTermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSubscriptionsIndexRoute = MainSubscriptionsIndexRouteImport.update({
  id: '/subscriptions/',
  path: '/subscriptions/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainRolesIndexRoute = MainRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainQualificationsIndexRoute = MainQualificationsIndexRouteImport.update({
  id: '/qualifications/',
  path: '/qualifications/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProvidersIndexRoute = MainProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProfileIndexRoute = MainProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPermissionsIndexRoute = MainPermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPagesIndexRoute = MainPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPackagesIndexRoute = MainPackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainNotificationsIndexRoute = MainNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainFaqsIndexRoute = MainFaqsIndexRouteImport.update({
  id: '/faqs/',
  path: '/faqs/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainDepartmentsIndexRoute = MainDepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCountriesIndexRoute = MainCountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainContactsIndexRoute = MainContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainClientsIndexRoute = MainClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCitiesIndexRoute = MainCitiesIndexRouteImport.update({
  id: '/cities/',
  path: '/cities/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainBannarsIndexRoute = MainBannarsIndexRouteImport.update({
  id: '/bannars/',
  path: '/bannars/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminsIndexRoute = MainAdminsIndexRouteImport.update({
  id: '/admins/',
  path: '/admins/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPagesTypeRoute = MainPagesTypeRouteImport.update({
  id: '/pages/$type',
  path: '/pages/$type',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPackagesIdRoute = MainPackagesIdRouteImport.update({
  id: '/packages/$id',
  path: '/packages/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCountriesIdRoute = MainCountriesIdRouteImport.update({
  id: '/countries/$id',
  path: '/countries/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCitiesIdRoute = MainCitiesIdRouteImport.update({
  id: '/cities/$id',
  path: '/cities/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPagesShowTypeRoute = MainPagesShowTypeRouteImport.update({
  id: '/pages/show/$type',
  path: '/pages/show/$type',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPackagesShowIdRoute = MainPackagesShowIdRouteImport.update({
  id: '/packages/show/$id',
  path: '/packages/show/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainClientsShowIdRoute = MainClientsShowIdRouteImport.update({
  id: '/clients/show/$id',
  path: '/clients/show/$id',
  getParentRoute: () => MainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/about': typeof MainAboutRoute
  '/analytics': typeof MainAnalyticsRoute
  '/settings': typeof MainSettingsRoute
  '/social-media': typeof MainSocialMediaRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof MainIndexRoute
  '/cities/$id': typeof MainCitiesIdRoute
  '/countries/$id': typeof MainCountriesIdRoute
  '/packages/$id': typeof MainPackagesIdRoute
  '/pages/$type': typeof MainPagesTypeRoute
  '/admins': typeof MainAdminsIndexRoute
  '/bannars': typeof MainBannarsIndexRoute
  '/cities': typeof MainCitiesIndexRoute
  '/clients': typeof MainClientsIndexRoute
  '/contacts': typeof MainContactsIndexRoute
  '/countries': typeof MainCountriesIndexRoute
  '/departments': typeof MainDepartmentsIndexRoute
  '/faqs': typeof MainFaqsIndexRoute
  '/notifications': typeof MainNotificationsIndexRoute
  '/packages': typeof MainPackagesIndexRoute
  '/pages': typeof MainPagesIndexRoute
  '/permissions': typeof MainPermissionsIndexRoute
  '/profile': typeof MainProfileIndexRoute
  '/providers': typeof MainProvidersIndexRoute
  '/qualifications': typeof MainQualificationsIndexRoute
  '/roles': typeof MainRolesIndexRoute
  '/subscriptions': typeof MainSubscriptionsIndexRoute
  '/terms': typeof MainTermsIndexRoute
  '/clients/show/$id': typeof MainClientsShowIdRoute
  '/packages/show/$id': typeof MainPackagesShowIdRoute
  '/pages/show/$type': typeof MainPagesShowTypeRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/about': typeof MainAboutRoute
  '/analytics': typeof MainAnalyticsRoute
  '/settings': typeof MainSettingsRoute
  '/social-media': typeof MainSocialMediaRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof MainIndexRoute
  '/cities/$id': typeof MainCitiesIdRoute
  '/countries/$id': typeof MainCountriesIdRoute
  '/packages/$id': typeof MainPackagesIdRoute
  '/pages/$type': typeof MainPagesTypeRoute
  '/admins': typeof MainAdminsIndexRoute
  '/bannars': typeof MainBannarsIndexRoute
  '/cities': typeof MainCitiesIndexRoute
  '/clients': typeof MainClientsIndexRoute
  '/contacts': typeof MainContactsIndexRoute
  '/countries': typeof MainCountriesIndexRoute
  '/departments': typeof MainDepartmentsIndexRoute
  '/faqs': typeof MainFaqsIndexRoute
  '/notifications': typeof MainNotificationsIndexRoute
  '/packages': typeof MainPackagesIndexRoute
  '/pages': typeof MainPagesIndexRoute
  '/permissions': typeof MainPermissionsIndexRoute
  '/profile': typeof MainProfileIndexRoute
  '/providers': typeof MainProvidersIndexRoute
  '/qualifications': typeof MainQualificationsIndexRoute
  '/roles': typeof MainRolesIndexRoute
  '/subscriptions': typeof MainSubscriptionsIndexRoute
  '/terms': typeof MainTermsIndexRoute
  '/clients/show/$id': typeof MainClientsShowIdRoute
  '/packages/show/$id': typeof MainPackagesShowIdRoute
  '/pages/show/$type': typeof MainPagesShowTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/_main/about': typeof MainAboutRoute
  '/_main/analytics': typeof MainAnalyticsRoute
  '/_main/settings': typeof MainSettingsRoute
  '/_main/social-media': typeof MainSocialMediaRoute
  '/auth/login': typeof AuthLoginRoute
  '/_main/': typeof MainIndexRoute
  '/_main/cities/$id': typeof MainCitiesIdRoute
  '/_main/countries/$id': typeof MainCountriesIdRoute
  '/_main/packages/$id': typeof MainPackagesIdRoute
  '/_main/pages/$type': typeof MainPagesTypeRoute
  '/_main/admins/': typeof MainAdminsIndexRoute
  '/_main/bannars/': typeof MainBannarsIndexRoute
  '/_main/cities/': typeof MainCitiesIndexRoute
  '/_main/clients/': typeof MainClientsIndexRoute
  '/_main/contacts/': typeof MainContactsIndexRoute
  '/_main/countries/': typeof MainCountriesIndexRoute
  '/_main/departments/': typeof MainDepartmentsIndexRoute
  '/_main/faqs/': typeof MainFaqsIndexRoute
  '/_main/notifications/': typeof MainNotificationsIndexRoute
  '/_main/packages/': typeof MainPackagesIndexRoute
  '/_main/pages/': typeof MainPagesIndexRoute
  '/_main/permissions/': typeof MainPermissionsIndexRoute
  '/_main/profile/': typeof MainProfileIndexRoute
  '/_main/providers/': typeof MainProvidersIndexRoute
  '/_main/qualifications/': typeof MainQualificationsIndexRoute
  '/_main/roles/': typeof MainRolesIndexRoute
  '/_main/subscriptions/': typeof MainSubscriptionsIndexRoute
  '/_main/terms/': typeof MainTermsIndexRoute
  '/_main/clients/show/$id': typeof MainClientsShowIdRoute
  '/_main/packages/show/$id': typeof MainPackagesShowIdRoute
  '/_main/pages/show/$type': typeof MainPagesShowTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/unauthorized'
    | '/about'
    | '/analytics'
    | '/settings'
    | '/social-media'
    | '/auth/login'
    | '/'
    | '/cities/$id'
    | '/countries/$id'
    | '/packages/$id'
    | '/pages/$type'
    | '/admins'
    | '/bannars'
    | '/cities'
    | '/clients'
    | '/contacts'
    | '/countries'
    | '/departments'
    | '/faqs'
    | '/notifications'
    | '/packages'
    | '/pages'
    | '/permissions'
    | '/profile'
    | '/providers'
    | '/qualifications'
    | '/roles'
    | '/subscriptions'
    | '/terms'
    | '/clients/show/$id'
    | '/packages/show/$id'
    | '/pages/show/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/unauthorized'
    | '/about'
    | '/analytics'
    | '/settings'
    | '/social-media'
    | '/auth/login'
    | '/'
    | '/cities/$id'
    | '/countries/$id'
    | '/packages/$id'
    | '/pages/$type'
    | '/admins'
    | '/bannars'
    | '/cities'
    | '/clients'
    | '/contacts'
    | '/countries'
    | '/departments'
    | '/faqs'
    | '/notifications'
    | '/packages'
    | '/pages'
    | '/permissions'
    | '/profile'
    | '/providers'
    | '/qualifications'
    | '/roles'
    | '/subscriptions'
    | '/terms'
    | '/clients/show/$id'
    | '/packages/show/$id'
    | '/pages/show/$type'
  id:
    | '__root__'
    | '/_main'
    | '/auth'
    | '/unauthorized'
    | '/_main/about'
    | '/_main/analytics'
    | '/_main/settings'
    | '/_main/social-media'
    | '/auth/login'
    | '/_main/'
    | '/_main/cities/$id'
    | '/_main/countries/$id'
    | '/_main/packages/$id'
    | '/_main/pages/$type'
    | '/_main/admins/'
    | '/_main/bannars/'
    | '/_main/cities/'
    | '/_main/clients/'
    | '/_main/contacts/'
    | '/_main/countries/'
    | '/_main/departments/'
    | '/_main/faqs/'
    | '/_main/notifications/'
    | '/_main/packages/'
    | '/_main/pages/'
    | '/_main/permissions/'
    | '/_main/profile/'
    | '/_main/providers/'
    | '/_main/qualifications/'
    | '/_main/roles/'
    | '/_main/subscriptions/'
    | '/_main/terms/'
    | '/_main/clients/show/$id'
    | '/_main/packages/show/$id'
    | '/_main/pages/show/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_main/social-media': {
      id: '/_main/social-media'
      path: '/social-media'
      fullPath: '/social-media'
      preLoaderRoute: typeof MainSocialMediaRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/analytics': {
      id: '/_main/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof MainAnalyticsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/terms/': {
      id: '/_main/terms/'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MainTermsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/subscriptions/': {
      id: '/_main/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof MainSubscriptionsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/roles/': {
      id: '/_main/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof MainRolesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/qualifications/': {
      id: '/_main/qualifications/'
      path: '/qualifications'
      fullPath: '/qualifications'
      preLoaderRoute: typeof MainQualificationsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/providers/': {
      id: '/_main/providers/'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof MainProvidersIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/profile/': {
      id: '/_main/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainProfileIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/permissions/': {
      id: '/_main/permissions/'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof MainPermissionsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/pages/': {
      id: '/_main/pages/'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof MainPagesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/packages/': {
      id: '/_main/packages/'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof MainPackagesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/notifications/': {
      id: '/_main/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof MainNotificationsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/faqs/': {
      id: '/_main/faqs/'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof MainFaqsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/departments/': {
      id: '/_main/departments/'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof MainDepartmentsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/countries/': {
      id: '/_main/countries/'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof MainCountriesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/contacts/': {
      id: '/_main/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof MainContactsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/clients/': {
      id: '/_main/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof MainClientsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/cities/': {
      id: '/_main/cities/'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof MainCitiesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/bannars/': {
      id: '/_main/bannars/'
      path: '/bannars'
      fullPath: '/bannars'
      preLoaderRoute: typeof MainBannarsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admins/': {
      id: '/_main/admins/'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof MainAdminsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/pages/$type': {
      id: '/_main/pages/$type'
      path: '/pages/$type'
      fullPath: '/pages/$type'
      preLoaderRoute: typeof MainPagesTypeRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/packages/$id': {
      id: '/_main/packages/$id'
      path: '/packages/$id'
      fullPath: '/packages/$id'
      preLoaderRoute: typeof MainPackagesIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/countries/$id': {
      id: '/_main/countries/$id'
      path: '/countries/$id'
      fullPath: '/countries/$id'
      preLoaderRoute: typeof MainCountriesIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/cities/$id': {
      id: '/_main/cities/$id'
      path: '/cities/$id'
      fullPath: '/cities/$id'
      preLoaderRoute: typeof MainCitiesIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/pages/show/$type': {
      id: '/_main/pages/show/$type'
      path: '/pages/show/$type'
      fullPath: '/pages/show/$type'
      preLoaderRoute: typeof MainPagesShowTypeRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/packages/show/$id': {
      id: '/_main/packages/show/$id'
      path: '/packages/show/$id'
      fullPath: '/packages/show/$id'
      preLoaderRoute: typeof MainPackagesShowIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/clients/show/$id': {
      id: '/_main/clients/show/$id'
      path: '/clients/show/$id'
      fullPath: '/clients/show/$id'
      preLoaderRoute: typeof MainClientsShowIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainAboutRoute: typeof MainAboutRoute
  MainAnalyticsRoute: typeof MainAnalyticsRoute
  MainSettingsRoute: typeof MainSettingsRoute
  MainSocialMediaRoute: typeof MainSocialMediaRoute
  MainIndexRoute: typeof MainIndexRoute
  MainCitiesIdRoute: typeof MainCitiesIdRoute
  MainCountriesIdRoute: typeof MainCountriesIdRoute
  MainPackagesIdRoute: typeof MainPackagesIdRoute
  MainPagesTypeRoute: typeof MainPagesTypeRoute
  MainAdminsIndexRoute: typeof MainAdminsIndexRoute
  MainBannarsIndexRoute: typeof MainBannarsIndexRoute
  MainCitiesIndexRoute: typeof MainCitiesIndexRoute
  MainClientsIndexRoute: typeof MainClientsIndexRoute
  MainContactsIndexRoute: typeof MainContactsIndexRoute
  MainCountriesIndexRoute: typeof MainCountriesIndexRoute
  MainDepartmentsIndexRoute: typeof MainDepartmentsIndexRoute
  MainFaqsIndexRoute: typeof MainFaqsIndexRoute
  MainNotificationsIndexRoute: typeof MainNotificationsIndexRoute
  MainPackagesIndexRoute: typeof MainPackagesIndexRoute
  MainPagesIndexRoute: typeof MainPagesIndexRoute
  MainPermissionsIndexRoute: typeof MainPermissionsIndexRoute
  MainProfileIndexRoute: typeof MainProfileIndexRoute
  MainProvidersIndexRoute: typeof MainProvidersIndexRoute
  MainQualificationsIndexRoute: typeof MainQualificationsIndexRoute
  MainRolesIndexRoute: typeof MainRolesIndexRoute
  MainSubscriptionsIndexRoute: typeof MainSubscriptionsIndexRoute
  MainTermsIndexRoute: typeof MainTermsIndexRoute
  MainClientsShowIdRoute: typeof MainClientsShowIdRoute
  MainPackagesShowIdRoute: typeof MainPackagesShowIdRoute
  MainPagesShowTypeRoute: typeof MainPagesShowTypeRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAboutRoute: MainAboutRoute,
  MainAnalyticsRoute: MainAnalyticsRoute,
  MainSettingsRoute: MainSettingsRoute,
  MainSocialMediaRoute: MainSocialMediaRoute,
  MainIndexRoute: MainIndexRoute,
  MainCitiesIdRoute: MainCitiesIdRoute,
  MainCountriesIdRoute: MainCountriesIdRoute,
  MainPackagesIdRoute: MainPackagesIdRoute,
  MainPagesTypeRoute: MainPagesTypeRoute,
  MainAdminsIndexRoute: MainAdminsIndexRoute,
  MainBannarsIndexRoute: MainBannarsIndexRoute,
  MainCitiesIndexRoute: MainCitiesIndexRoute,
  MainClientsIndexRoute: MainClientsIndexRoute,
  MainContactsIndexRoute: MainContactsIndexRoute,
  MainCountriesIndexRoute: MainCountriesIndexRoute,
  MainDepartmentsIndexRoute: MainDepartmentsIndexRoute,
  MainFaqsIndexRoute: MainFaqsIndexRoute,
  MainNotificationsIndexRoute: MainNotificationsIndexRoute,
  MainPackagesIndexRoute: MainPackagesIndexRoute,
  MainPagesIndexRoute: MainPagesIndexRoute,
  MainPermissionsIndexRoute: MainPermissionsIndexRoute,
  MainProfileIndexRoute: MainProfileIndexRoute,
  MainProvidersIndexRoute: MainProvidersIndexRoute,
  MainQualificationsIndexRoute: MainQualificationsIndexRoute,
  MainRolesIndexRoute: MainRolesIndexRoute,
  MainSubscriptionsIndexRoute: MainSubscriptionsIndexRoute,
  MainTermsIndexRoute: MainTermsIndexRoute,
  MainClientsShowIdRoute: MainClientsShowIdRoute,
  MainPackagesShowIdRoute: MainPackagesShowIdRoute,
  MainPagesShowTypeRoute: MainPagesShowTypeRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
